"""
Shared Tokenizer Module

Provides unified tokenization for all BM25/vocabulary operations.
Ensures consistent text processing across vocabulary extraction and retrieval.

Usage:
    from src.core.utils.tokenizer import tokenize, TokenizerConfig, STOPWORDS

    # Default tokenization (min_length=3, filter stopwords)
    tokens = tokenize("This is some text with medical terminology.")

    # Custom config for retrieval (no stopword filtering)
    config = TokenizerConfig(filter_stopwords=False, min_length=1)
    tokens = tokenize("What are the plaintiff's claims?", config)
"""

import re
from dataclasses import dataclass, field

# Standard regex pattern preserving hyphens and apostrophes
# Matches words that:
# - Start with a letter
# - Can contain letters, digits, apostrophes, and hyphens
# - End with a letter or digit
# Also matches single letters
TOKEN_PATTERN = re.compile(r"\b[a-zA-Z][a-zA-Z0-9'-]*[a-zA-Z0-9]\b|\b[a-zA-Z]\b")

# Unified stopwords (merged from all BM25 implementations)
# These are common words that don't carry meaning for search/extraction
# Session 58: Expanded with body parts, transcript fillers, and more common nouns
STOPWORDS: frozenset[str] = frozenset(
    {
        # Articles
        "a",
        "an",
        "the",
        # Conjunctions
        "and",
        "or",
        "but",
        "nor",
        "so",
        "yet",
        # Prepositions
        "in",
        "on",
        "at",
        "to",
        "for",
        "of",
        "with",
        "by",
        "from",
        "as",
        "about",
        "against",
        "between",
        "into",
        "through",
        "during",
        "before",
        "after",
        "above",
        "below",
        "up",
        "down",
        "out",
        "off",
        "over",
        "under",
        # Be verbs
        "is",
        "was",
        "are",
        "were",
        "been",
        "be",
        "being",
        "am",
        # Have verbs
        "have",
        "has",
        "had",
        "having",
        # Do verbs
        "do",
        "does",
        "did",
        "doing",
        # Modal verbs
        "will",
        "would",
        "could",
        "should",
        "may",
        "might",
        "must",
        "shall",
        "can",
        "need",
        "dare",
        "ought",
        "used",
        # Pronouns
        "i",
        "you",
        "he",
        "she",
        "it",
        "we",
        "they",
        "me",
        "him",
        "her",
        "us",
        "them",
        "my",
        "your",
        "his",
        "its",
        "our",
        "their",
        "mine",
        "yours",
        "hers",
        "ours",
        "theirs",
        # Demonstratives
        "this",
        "that",
        "these",
        "those",
        # Interrogatives
        "what",
        "which",
        "who",
        "whom",
        "whose",
        "where",
        "when",
        "why",
        "how",
        # Quantifiers
        "all",
        "each",
        "every",
        "both",
        "few",
        "more",
        "most",
        "other",
        "some",
        "such",
        "any",
        "many",
        "much",
        # Negation/affirmation
        "no",
        "not",
        "yes",
        # Adverbs
        "only",
        "own",
        "same",
        "than",
        "too",
        "very",
        "just",
        "also",
        "now",
        "here",
        "there",
        "then",
        "once",
        "again",
        "further",
        "well",
        "back",
        "even",
        "still",
        "already",
        "always",
        "never",
        # Directional/positional (common in medical/legal but not technical)
        "left",
        "right",
        "within",
        "without",
        "upon",
        "around",
        "along",
        # Common verbs
        "said",
        "says",
        "say",
        "made",
        "make",
        "making",
        "get",
        "got",
        "give",
        "gave",
        "take",
        "took",
        "taken",
        "put",
        "read",
        "went",
        "come",
        "came",
        "know",
        "knew",
        "think",
        "thought",
        "see",
        "saw",
        "seen",
        "look",
        "looked",
        "use",
        "find",
        "found",
        "tell",
        "told",
        "ask",
        "asked",
        "seem",
        "seemed",
        "feel",
        "try",
        "tried",
        "leave",
        "call",
        "called",
        "keep",
        "kept",
        "let",
        "begin",
        "show",
        "shown",
        "hear",
        "heard",
        "play",
        "run",
        "move",
        "moved",
        "live",
        "believe",
        "hold",
        "held",
        "bring",
        "brought",
        "happen",
        "write",
        "written",
        "provide",
        "sit",
        "stand",
        "lose",
        "lost",
        "pay",
        "paid",
        "meet",
        "met",
        "include",
        "included",
        "continue",
        "set",
        "learn",
        "change",
        "lead",
        "led",
        "understand",
        "watch",
        "follow",
        "stop",
        "create",
        "speak",
        "allow",
        "add",
        "spend",
        "grow",
        "open",
        "walk",
        "win",
        "offer",
        "remember",
        "consider",
        "appear",
        "buy",
        "wait",
        "serve",
        "die",
        "send",
        "sent",
        "expect",
        "build",
        "stay",
        "fall",
        "fell",
        "cut",
        "reach",
        "kill",
        "remain",
        "suggest",
        "raise",
        "pass",
        "sell",
        "require",
        "report",
        "decide",
        "pull",
        # Other common words
        "if",
        "because",
        "until",
        "while",
        "like",
        "way",
        "thing",
        "things",
        "time",
        "times",
        "year",
        "years",
        "day",
        "days",
        "week",
        "weeks",
        "month",
        "people",
        "person",
        "man",
        "men",
        "woman",
        "women",
        "child",
        "children",
        "world",
        "life",
        "hand",
        "hands",
        "part",
        "parts",
        "place",
        "case",
        "cases",
        "point",
        "points",
        "fact",
        "facts",
        "home",
        "water",
        "room",
        "mother",
        "area",
        "money",
        "story",
        "number",
        "numbers",
        "lot",
        "far",
        "away",
        "small",
        "large",
        "big",
        "long",
        "little",
        "old",
        "new",
        "good",
        "great",
        "high",
        "different",
        "important",
        "young",
        "national",
        "next",
        "early",
        "last",
        "first",
        "second",
        "third",
        "certain",
        "able",
        "best",
        "better",
        "full",
        "sure",
        "enough",
        "late",
        "hard",
        "real",
        "whole",
        "clear",
        "recent",
        "possible",
        "free",
        "several",
        "less",
        "public",
        "bad",
        "true",
        # Legal document common words (not terms)
        "copy",
        "copies",
        "page",
        "pages",
        "line",
        "lines",
        "file",
        "filed",
        "date",
        "dated",
        "regarding",
        "matter",
        "order",
        "ordered",
        "pursuant",
        "thereof",
        "herein",
        "hereby",
        "wherein",
        "therefore",
        "attached",
        "exhibit",
        "exhibits",
        "document",
        "documents",
        # === Session 58 additions ===
        # Basic body parts (not medical terms - those are valuable)
        "age",
        "body",
        "head",
        "face",
        "eye",
        "eyes",
        "ear",
        "ears",
        "nose",
        "mouth",
        "arm",
        "arms",
        "leg",
        "legs",
        "foot",
        "feet",
        "knee",
        "knees",
        "side",
        "sides",
        "neck",
        "shoulder",
        "shoulders",
        "chest",
        "stomach",
        "hip",
        "hips",
        "finger",
        "fingers",
        "thumb",
        "toe",
        "toes",
        "wrist",
        "ankle",
        "elbow",
        # Transcript filler words and common responses
        "okay",
        "ok",
        "um",
        "uh",
        "yeah",
        "yep",
        "nope",
        "alright",
        "correct",
        "incorrect",
        "false",
        "fair",
        "fine",
        "sorry",
        "please",
        "thank",
        "thanks",
        "welcome",
        "hello",
        "hi",
        "bye",
        "goodbye",
        # Time-related common words
        "hour",
        "hours",
        "minute",
        "minutes",
        "seconds",
        "moment",
        "today",
        "yesterday",
        "tomorrow",
        "morning",
        "afternoon",
        "evening",
        "night",
        "months",
        "ago",
        "later",
        "soon",
        "sometime",
        "sometimes",
        "often",
        "usually",
        # More common nouns
        "state",
        "states",
        "city",
        "town",
        "county",
        "country",
        "street",
        "road",
        "office",
        "building",
        "floor",
        "door",
        "window",
        "car",
        "vehicle",
        "phone",
        "job",
        "work",
        "business",
        "company",
        "name",
        "names",
        "address",
        "email",
        "question",
        "questions",
        "answer",
        "answers",
        "problem",
        "problems",
        "issue",
        "issues",
        "reason",
        "reasons",
        "result",
        "results",
        "example",
        "information",
        "idea",
        "ideas",
        "kind",
        "type",
        "types",
        "sort",
        "level",
        "record",
        "records",
        "note",
        "notes",
        "letter",
        "letters",
        "form",
        "forms",
        "service",
        "services",
        "system",
        "process",
        "program",
        "group",
        "family",
        "father",
        "brother",
        "sister",
        "son",
        "daughter",
        "husband",
        "wife",
        "friend",
        # More common adjectives
        "wrong",
        "similar",
        "normal",
        "regular",
        "general",
        "specific",
        "particular",
        "main",
        "major",
        "minor",
        "basic",
        "simple",
        "special",
        "common",
        "local",
        "current",
        "previous",
        "prior",
        "former",
        "entire",
        "complete",
        "total",
        "final",
        "original",
        "additional",
        # More common verbs
        "going",
        "saying",
        "getting",
        "looking",
        "coming",
        "taking",
        "working",
        "trying",
        "using",
        "talking",
        "thinking",
        "asking",
        "telling",
        "helping",
        "turning",
        "starting",
        "ending",
        "beginning",
        "finishing",
        "sitting",
        "standing",
        "walking",
        "running",
        "driving",
        "living",
        "happening",
        "causing",
        "meaning",
        "feeling",
        "becoming",
    }
)


@dataclass
class TokenizerConfig:
    """
    Configuration for tokenization behavior.

    Attributes:
        min_length: Minimum token length (default 3)
        filter_stopwords: Whether to remove stopwords (default True)
        stopwords: Set of stopwords to filter (default STOPWORDS)
    """

    min_length: int = 3
    filter_stopwords: bool = True
    stopwords: frozenset[str] = field(default_factory=lambda: STOPWORDS)


# Default config singleton for common use case
_DEFAULT_CONFIG = TokenizerConfig()

# Retrieval config (no stopword filtering, min length 1)
RETRIEVAL_CONFIG = TokenizerConfig(
    min_length=1,
    filter_stopwords=False,
)


def tokenize(text: str, config: TokenizerConfig | None = None) -> list[str]:
    """
    Tokenize text into lowercase words.

    Uses consistent regex pattern across all BM25/vocabulary operations.
    Optionally filters stopwords and short tokens.

    Args:
        text: Input text to tokenize
        config: Optional TokenizerConfig. If None, uses default settings
                (min_length=3, filter_stopwords=True)

    Returns:
        List of lowercase word tokens

    Example:
        >>> tokenize("The plaintiff's medical records show...")
        ['plaintiff', 'medical', 'records', 'show']

        >>> tokenize("Who?", RETRIEVAL_CONFIG)
        ['who']
    """
    if config is None:
        config = _DEFAULT_CONFIG

    # Extract words using standard pattern
    words = TOKEN_PATTERN.findall(text.lower())

    # Apply filters
    result = []
    for word in words:
        # Length filter
        if len(word) < config.min_length:
            continue

        # Stopword filter
        if config.filter_stopwords and word in config.stopwords:
            continue

        result.append(word)

    return result


def tokenize_simple(text: str) -> list[str]:
    """
    Simple tokenization for retrieval (no filtering).

    Preserves all words including short ones and stopwords.
    Use this for query tokenization where every word matters.

    Args:
        text: Input text to tokenize

    Returns:
        List of lowercase word tokens
    """
    return tokenize(text, RETRIEVAL_CONFIG)
