"""
Combined Export Module

Session 73: Exports both vocabulary and Q&A results in a single document.

This creates a unified report with:
1. Names & Vocabulary table
2. Questions & Answers section

Supports Word (.docx) and PDF formats using the DocumentBuilder pattern.
"""

import logging

from src.core.export.base import DocumentBuilder
from src.core.export.qa_exporter import export_qa_results
from src.core.export.vocab_exporter import export_vocabulary

logger = logging.getLogger(__name__)


def export_combined(
    vocab_data: list[dict],
    qa_results: list,
    builder: DocumentBuilder,
    include_vocab_details: bool = False,
    include_qa_verification: bool = True,
    title: str = "Document Analysis Report",
) -> None:
    """
    Export both vocabulary and Q&A results to a single document.

    Args:
        vocab_data: List of vocabulary dicts
        qa_results: List of QAResult objects
        builder: DocumentBuilder instance (Word or PDF)
        include_vocab_details: Include algorithm columns in vocabulary table
        include_qa_verification: Include verification coloring in Q&A
        title: Document title
    """
    logger.debug(
        "Creating combined report: %d terms, %d Q&A pairs", len(vocab_data), len(qa_results)
    )

    # Document title
    builder.add_heading(title, level=1)
    builder.add_paragraph("")  # Spacer

    # Section 1: Vocabulary
    if vocab_data:
        export_vocabulary(vocab_data, builder, include_vocab_details)
        builder.add_paragraph("")  # Spacer after table

    # Section 2: Q&A
    if qa_results:
        export_qa_results(qa_results, builder, include_qa_verification)

    # Footer note
    builder.add_paragraph("")
    builder.add_paragraph("Generated by CasePrepd")

    logger.debug("Combined report generation complete")
